/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    java
    `maven-publish`
    id("io.papermc.paperweight.userdev") version "1.3.7"
}

repositories {
    mavenCentral()
    mavenLocal()
    maven {
        url = uri("https://repo.papermc.io/repository/maven-public/")
        //url = uri("https://jitpack.io")
        url = uri("https://repo.maven.apache.org/maven2/")
        url = uri("https://mvn.intellectualsites.com/content/groups/public/")
    }

}

dependencies {
    implementation(platform("com.intellectualsites.bom:bom-1.18.x:1.12"))
    compileOnly("com.fastasyncworldedit:FastAsyncWorldEdit-Core")
    compileOnly("com.fastasyncworldedit:FastAsyncWorldEdit-Bukkit") { isTransitive = false }
    compileOnly("io.papermc.paper:paper-api:1.19-R0.1-SNAPSHOT")
    paperDevBundle("1.19-R0.1-SNAPSHOT")
}

group = "com.github.TimEpsilon"
version = "1.0"
description = "ProjectHecate"
java.sourceCompatibility = JavaVersion.VERSION_17


tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}
